language: php

php:
  - 5.4
#  - 5.5
#  - 5.6

mysql:
  database: drupal
  username: root
  encoding: utf8

env:
  - PATH=$PATH:/home/travis/.composer/vendor/bin

before_install:
  # Update Composer so that the Drush installation doesn't fail.
  - composer selfupdate

install:
  - sudo apt-get update
  # Install Apache.
  - sudo apt-get install apache2 libapache2-mod-fastcgi

  # Set up PHP-FPM.
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  # Set up the Apache vhost.
  - sudo cp -f $TRAVIS_BUILD_DIR/.travis/apache-vhost.conf /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$TRAVIS_BUILD_DIR/../drupal?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart

  # Install Drush.
  - composer global require drush/drush:dev-master

before_script:
  # Checkout a directory structure with all dependencies.
  - git clone --depth 1 --branch 8.0.x http://git.drupal.org/project/drupal.git $TRAVIS_BUILD_DIR/../drupal
  - git clone --branch 8.x-1.x https://github.com/dickolsson/drupal-key_value.git $TRAVIS_BUILD_DIR/../drupal/modules/key_value
  - git clone --branch 8.x-1.x https://github.com/dickolsson/drupal-multiversion.git $TRAVIS_BUILD_DIR/../drupal/modules/multiversion
  - git clone --branch 8.x-1.x https://github.com/dickolsson/drupal-relaxed.git $TRAVIS_BUILD_DIR/../drupal/modules/relaxed
  - git clone --branch 8.x-0.x https://github.com/dickolsson/drupal-replication.git $TRAVIS_BUILD_DIR/../drupal/modules/replication
  - ln -s $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/../drupal/modules/deploy

  # Install the site that will host our tests.
  - cd $TRAVIS_BUILD_DIR/../drupal
  - php -d sendmail_path=`which true` ~/.composer/vendor/bin/drush.php --yes site-install --db-url=mysql://root:@127.0.0.1/drupal testing

  # Enable required modules and ignore any output to not break the test.
  - drush --yes pm-enable serialization key_value replication multiversion rest basic_auth relaxed deploy || true

script:
  # Run the tests and make sure we exit with the right status.
  - php scripts/run-tests.sh --verbose --color --php `which php` --url http://127.0.0.1 --xml /tmp "deploy"
  - if [[ `grep -e 'type="\(failure\|exception\)"\|Fatal error' /tmp/*TestCase.xml` ]]; then exit 1; fi
