deploy.endpoint.*:
  type: config_entity
  label: 'Endpoint config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'UUID'
    authentication:
      type: string
      label: 'Authentication'
    plugin:
      type: string
      label: 'Plugin'
    settings:
      type: deploy.endpoint.settings.[%parent.plugin]

deploy.endpoint.settings.*:
  type: endpoint_settings
