deploy.endpoint.*:
  type: config_entity
  label: 'Endpoint config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'UUID'
    plugin:
      type: string
      label: 'Plugin'
    settings:
      type: deploy.endpoint.configuration.[%parent.plugin]

deploy.endpoint.configuration.*:
  type: endpoint_configuration
